import { useParams } from "react-router-dom"
import { Button, Divider, Grid2, Table, TableBody, TableCell, TableContainer, TableRow, TextField, Typography } from "@mui/material";
import { useFetchProductsDetailsQuery } from "./catalogApi";

export default function ProductDetails() {
  // Extracting the product ID from the URL parameters
  // This allows us to fetch the specific product details based on the ID
  const { id } = useParams();

  // Using the custom hook generated by RTK Query to fetch product details
  // The product ID is converted to a number before passing it to the query => +id
  const {data: product, isLoading} = useFetchProductsDetailsQuery(id ? +id : 0);

  const productDetails = [
    {label: 'Name', value: product?.name},
    {label: 'Description', value: product?.description},
    {label: 'Type', value: product?.type},
    {label: 'Brand', value: product?.brand},
    {label: 'Quantity in Stock', value: product?.quantityInStock},
  ]

  if (!product || isLoading) return <div>Loading...</div>;

  return (
    <Grid2 container spacing={6} maxWidth="lg" sx={{ mx: "auto" }}>
      <Grid2 size={6}>
        <img src={product.pictureUrl} alt={product.name} style={{ width: '100%' }} />
      </Grid2>
      <Grid2 size={6}>
        <Typography variant="h3">{product.name}</Typography>
        <Divider sx={{ mb: 2 }} />
        <Typography variant="h4" color="secondary">${(product.price / 100).toFixed(2)}</Typography>
        <TableContainer>
          <Table sx={{'& td': { fontSize: '1rem' } }}>
            <TableBody>
              {/* loop through the list of produCtDetails objects and put them in a table row
               and their values in the table cells */}
              {productDetails.map((details, index) => (
                <TableRow key={index}>
                  <TableCell sx={{fontWeight: 'bold'}}>{details.label}</TableCell>
                  <TableCell>{details.value}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </TableContainer>
        <Grid2 container spacing={2} marginTop={3}>
          <Grid2 size={6}>
            <TextField
              variant="outlined"
              type="number"
              label="Quantity in Cart"
              fullWidth
              defaultValue={1}
            />
          </Grid2>
          <Grid2 size={6}>
            <Button
              sx={{ height: '55px' }}
              color="primary"
              size="large"
              variant="contained"
              fullWidth
            >
              Add to Cart
            </Button>
          </Grid2>
        </Grid2>
      </Grid2>
    </Grid2>
  )
}